---

- name: Create Prometheus systemd directory
  file:
    dest: "/etc/systemd/system"
    state: directory
    recurse: yes

- name: Template prometheus systemd service file
  register: systemd_service_template
  template:
    src: "prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
  notify:
    - reload systemd-daemon
    - restart prometheus