---

- name: Create Prometheus Alert Manager release directory
  file:
    dest: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "/opt/prometheus_alertmanager_v{{ prometheus_alertmanager_version }}"
    - "{{ prometheus_alertmanager_config_dir }}"

- name: Install dependencies thru apt
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "build-essential"
    - "libc6-dev"

- name: Download Prometheus Alert Manager release tarball
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-amd64.tar.gz"
    dest: "/opt/prometheus_alertmanager_v{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-amd64.tar.gz"

- name: Unarchive Prometheus tarball
  unarchive:
    src: "/opt/prometheus_alertmanager_v{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-amd64.tar.gz"
    dest: "/opt/prometheus_alertmanager_v{{ prometheus_alertmanager_version }}/"
    remote_src: yes
    creates: "/opt/prometheus_alertmanager_v{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-amd64/alertmanager"

- name: Ensure 775 permissions on Prometheus Alert Manager binary
  file:
    dest: "/opt/prometheus_alertmanager_v{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-amd64/alertmanager"
    mode: "0775"

- name: Symlink Prometheus Alert Manager binary to exec dir
  file:
    src: "/opt/prometheus_alertmanager_v{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-amd64/alertmanager"
    dest: "/usr/local/bin/alertmanager"
    state: link

- name: Fail when expected and actual prometheus versions do not match
  shell: alertmanager -version
  register: alertmanager_version_output
  failed_when: prometheus_alertmanager_version not in alertmanager_version_output.stdout

- name: Template config file from prometheus_alertmanager_config_file variable
  copy:
    content: "{{ prometheus_alertmanager_config_hash | to_nice_yaml }}"
    dest: "{{ prometheus_alertmanager_config_file }}"

- name: Include xenial when distro greater than 14.04
  when: ansible_distribution_version|version_compare('14.04','>')
  include: xenial.yml

- name: Include trusty when distro less than 16.04
  when: ansible_distribution_version|version_compare('16.04','<')
  include: trusty.yml
