---

- name: Create Alert Manager upstart directory
  file:
    dest: "/etc/init"
    state: directory
    recurse: yes

- name: Template Alert Manager upstart service file
  register: upstart_service_template
  template:
    src: "alertmanager.conf.j2"
    dest: "/etc/init/alertmanager.conf"
  notify:
    - "restart_alertmanager_{{ ansible_distribution_version }}"

- name: Ensure alertmanager service started and enabled
  service:
    name: alertmanager
    enabled: yes
    state: started
