---

- name: Ensure directory exists
  file:
    dest: "{{ nagios_checks_templates_dir }}"
    recurse: yes
    state: directory

- name: Template specified files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items: "{{ nagios_checks_templates_list }}"
