---

- name: Ensure deb downloaded and installed
  apt:
    deb: "https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_4.4.3_amd64.deb"
    #allow_unauthenticated: yes
    state: present

- name: Template config files for grafana
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: grafana.conf.j2
      dest: "{{ grafana_conf_dir }}/grafana.ini"
  notify:
    - Restart grafana-server

#- name: Ensure grafana starts on boot
#  command: "update-rc.d {{ grafana_service }} defaults 95 10"

- name: Ensure grafana started and enabled
  service:
    name: "{{ grafana_service }}"
    state: started
    enabled: yes
