---

- name: Unarchive Prometheus Consul Exporter release tarball
  unarchive:
    src: "https://github.com/prometheus/consul_exporter/releases/download/v{{ prometheus_consul_exporter_version }}/consul_exporter-{{ prometheus_consul_exporter_version }}.linux-amd64.tar.gz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/consul_exporter-{{ prometheus_consul_exporter_version }}.linux-amd64/consul_exporter"

- name: Ensure 775 permissions on Prometheus Consul Exporter binary
  file:
    dest: "/opt/consul_exporter-{{ prometheus_consul_exporter_version }}.linux-amd64/consul_exporter"
    mode: "0775"

- name: Symlink Prometheus Consul Exporter binary to exec dir
  file:
    src: "/opt/consul_exporter-{{ prometheus_consul_exporter_version }}.linux-amd64/consul_exporter"
    dest: "/usr/local/bin/consul_exporter"
    state: link

- name: Include xenial when distro greater than 14.04
  when: ansible_distribution_version|version_compare('14.04','>')
  include: xenial.yml

- name: Include trusty when distro less than 16.04
  when: ansible_distribution_version|version_compare('16.04','<')
  include: trusty.yml
