---

- name: restart_node_exporter_14.04
  service:
    name: node_exporter
    state: restarted

- name: restart_node_exporter_16.04
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
