---
core_servers:
  hosts: [ core1.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key" 
prometheus_servers:
  hosts: [ prometheus1.lan, prometheus2.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
prometheus_client_servers:
  hosts: [ client1.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
consul_servers:
  hosts: [ consul1.lan, consul2.lan, consul3.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
consul_client_servers:
  children: [ prometheus_client_servers,prometheus_servers ]
prometheus_node_exporter_servers:
  children: [ prometheus_servers, prometheus_client_servers, consul_servers, core_servers ]
prometheus_consul_exporter_servers:
  children: [ consul_servers ]
prometheus_alertmanager_servers:
  children: [ prometheus_servers ]
all:
  children: [ prometheus_servers, prometheus_client_servers, consul_servers, consul_client_servers ]
_meta:
  hostvars:
    core1.lan:
      vagrant_ip: "172.136.1.11"
      vagrant_box: "ubuntu/trusty64"
    prometheus1.lan:
      vagrant_ip: "172.136.4.11"
      vagrant_box: "ubuntu/trusty64"
    prometheus2.lan:
      vagrant_ip: "172.136.4.12"
      vagrant_box: "ubuntu/trusty64"
    client1.lan:
      vagrant_ip: "172.136.3.11"
      vagrant_box: "ubuntu/trusty64"
    consul1.lan:
      vagrant_ip: "172.136.2.11"
      vagrant_box: "ubuntu/trusty64"
    consul2.lan:
      vagrant_ip: "172.136.2.12"
      vagrant_box: "ubuntu/trusty64"
    consul3.lan:
      vagrant_ip: "172.136.2.13"
      vagrant_box: "ubuntu/trusty64"
