---

- name: Install Consul servers
  hosts: consul_servers
  become: yes
  become_user: root
  vars_files:
    - vars/makevault.yml
  roles:
    - role: consul
      consul_type: "server"
      consul_version: "0.9.1"
      consul_log_level: "DEBUG"
      consul_advertise_iface: "eth1"
      consul_server_list_lookup_interface: 'ansible_eth1'
      consul_advertise_addr: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
      consul_http_addr: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
      consul_https_addr: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
      consul_dns_addr: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
      consul_server_list: "{{ groups['consul_servers'] }}"
      consul_services_hash:
        services:
          - name: prometheus
            tags:
            - prometheus
            - node-exporter
            address: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
            port: 9100
            checks:
            - id: prometheus_check_3
              name: Prometheus node-exporter TCP on port 9100
              tcp: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}:9100"
              interval: 10s
              timeout: 1s
