---

- name: Set global facts on hosts
  hosts: all
  gather_facts: yes
  vars_files:
    - vars/makevault.yml
  become: yes
  become_user: root
  pre_tasks:
    - name: Set facts for playbook
      set_fact:
        fact_bind9_allowed_subnets:
          - "172.136.1.0/24"
          - "172.136.2.0/24"
          - "172.136.3.0/24"
          - "172.136.4.0/24"
          - "172.136.5.0/24"
          - "172.136.6.0/24"

- name: Install Bind9
  hosts: core1.lan
  become: yes
  become_user: root
  vars_files:
    - vars/makevault.yml
  roles:
    - role: bind9
      bind9_type: master
      bind9_listen: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
      bind9_named_allow_transfer: "any"
      bind9_named_forward_zones:
        - name: "lan"
          path: "/etc/bind/zones/master"
          file: "db.lan"
          hosts:
            - 172.136.1.12
      bind9_named_reverse_zones:
        - name: "1.136.172.in-addr.arpa"
          path: "/etc/bind/zones/master"
          file: "db.1.136.172"
          hosts:
            - 172.136.1.12
        - name: "2.136.172.in-addr.arpa"
          path: "/etc/bind/zones/master"
          file: "db.2.136.172"
          hosts:
            - 172.136.1.12
        - name: "3.136.172.in-addr.arpa"
          path: "/etc/bind/zones/master"
          file: "db.3.136.172"
          hosts:
            - 172.136.1.12
        - name: "4.136.172.in-addr.arpa"
          path: "/etc/bind/zones/master"
          file: "db.4.136.172"
          hosts:
            - 172.136.1.12
      bind9_named_forwarder_zones:
        - name: "consul"
          hosts: "{{ hostvars | server_group_ip_port_map_v2(groups['consul_servers'], 'ansible_eth1', '8600') }}"
      bind9_named_acls:
        - name: trusted
          allowed: "{{ fact_bind9_allowed_subnets }}"
