---

- name: Create Node Exporter systemd directory
  file:
    dest: "/etc/systemd/system"
    state: directory
    recurse: yes

- name: Template Node Exporter systemd service file
  register: systemd_service_template
  template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
  notify:
    - "restart_node_exporter_{{ ansible_distribution_version }}"

- name: Ensure node_exporter service started
  systemd:
    name: node_exporter
    state: started
